spring:
  application:
    name: job-worker
    
  datasource:
    url: jdbc:postgresql://localhost:5432/jobsdb
    username: postgres
    password: jobss
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

worker:
  poll:
    interval:
      ms: 2000
  processing:
    timeout:
      seconds: 30
```

